""" eve_ui.py --

 UI generated by GUI Builder Build 146 on 2010-01-25 23:08:35 from:
    F:/geprogge/eve tools/eve.ui
THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
The associated callback file should be modified instead.
"""

import Tkinter
import os # needed for relative image paths

# Using new-style classes: create empty base class object
# for compatibility with older python interps
#if sys.version_info < (2, 2):
#    class object:
#        pass

class Eve(object):
    _images = [] # Holds image refs to prevent GC
    def __init__(self, root):
        self.destid = Tkinter.StringVar(root)
        self.startid = Tkinter.StringVar(root)


        # Widget Initialization
        self.start = Tkinter.Entry(root,
            width = 0,
        )
        self.destination = Tkinter.Entry(root,
            width = 0,
        )
        self.calc = Tkinter.Button(root,
            text = "calc",
        )
        self._label_1 = Tkinter.Label(root,
            textvariable = self.startid,
        )
        self._label_2 = Tkinter.Label(root,
            textvariable = self.destid,
        )

        # widget commands

        self.start.configure(
            invalidcommand = self.start_invalidcommand
        )
        self.start.configure(
            validatecommand = self.start_validatecommand
        )
        self.start.configure(
            xscrollcommand = self.start_xscrollcommand
        )
        self.destination.configure(
            invalidcommand = self.destination_invalidcommand
        )
        self.destination.configure(
            validatecommand = self.destination_validatecommand
        )
        self.destination.configure(
            xscrollcommand = self.destination_xscrollcommand
        )
        self.calc.configure(
            command = self.calc_command
        )


        # Geometry Management
        self.start.grid(
            in_    = root,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "ew"
        )
        self.destination.grid(
            in_    = root,
            column = 3,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "ew"
        )
        self.calc.grid(
            in_    = root,
            column = 4,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._label_1.grid(
            in_    = root,
            column = 1,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._label_2.grid(
            in_    = root,
            column = 3,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )


        # Resize Behavior
        root.grid_rowconfigure(1, weight = 0, minsize = 40, pad = 0)
        root.grid_rowconfigure(2, weight = 0, minsize = 41, pad = 0)
        root.grid_columnconfigure(1, weight = 0, minsize = 129, pad = 0)
        root.grid_columnconfigure(2, weight = 0, minsize = 34, pad = 0)
        root.grid_columnconfigure(3, weight = 0, minsize = 152, pad = 0)
        root.grid_columnconfigure(4, weight = 0, minsize = 40, pad = 0)


